### PR TITLE
Add developer guide

### PR DESCRIPTION
**Pull request by critzo**
This PR adds a developer guide page. The branch is not previewed on Github pages, so I've provided a screenshot below of the page and menu item.

screenshot from 2018-01-30 12-56-07

@georgiamoon @pboothe PTAL?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/345)

### CODE REVIEW

**Comment by pboothe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[_pages/developers.md, line 27 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47dp1JHyBmnMG57BNk:-L47dp1JHyBmnMG57BNl:b-76zbgp) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L27)):*
> ```Markdown
> ### How to select an M-Lab server for testing
> 
> Client developers are welcome to use any production M-Lab site according to their preference and testing plans. However, developers should keep in mind that certain servers can encounter disruption or administrative maintenance with short to no notice. Planning should allow for changes in availability for servers.
> ```

The easiest and recommended way to deal with changing server availability is to use our directory service.

---

*[_pages/developers.md, line 29 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47Zqx-WHpcxW_gnNmO:-L47Zqx-WHpcxW_gnNmP:b-l8x3xt) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L29)):*
> Applications may want to invalidate the cache and query mlab-ns again when a previously cached mlab-ns server fails to connect.

Should be: At a minimum, we recommend applications invalidate their cache and query mlab-ns again when the connection fails to a server name cached from an old mlab-ns response.

---

*[_pages/developers.md, line 41 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47_LVxnAymZbn91aEf:-L47_LVxnAymZbn91aEg:bn2y5x9) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L41)):*
> ```Markdown
> * NDT
> * Neubot
> * NPAD
> ```

Remove NPAD, add ndt_ssl. Nobody uses NPAD, and we are not planning on porting it forward.

---

*[_pages/developers.md, line 52 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47_shlycdHomofNyKe:-L47_shlycdHomofNyKf:bps54a8) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L52)):*
> Note that the user is not required to consent to this information being sent.

The mlab-ns logs are not governed by M-Lab's open-data policy. Queries to mlab-ns may be sent prior to acquiring user consent to run the actual test.

---

*[_pages/developers.md, line 52 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47aKX9a4DVGwOM4WxQ:-L47aKX9a4DVGwOM4WxR:bkc5j75) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L52)):*
> Finally, using this information ...

Using the location from AppEngine, ...

---

*[_pages/developers.md, line 56 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47aVsWfGYba7PnBNrs:-L47aVsWfGYba7PnBNrt:byfjop5) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L56)):*
> ```Markdown
> ### Where does M-Lab place servers?
> 
> The M-Lab platform is designed to provide broadband users with measurements that reflect their actual Internet experience. To align with this mission, the M-Lab sites that users conduct tests against are typically located in networks that host Internet content or key infrastructure locations. These providers tend to be Internet exchanges, transit networks, or prominent hosting companies. The M-­Lab sites are typically physically collocated in the same building as major network providers’ routers.
> ```

remove 'actual'

---

*[_pages/developers.md, line 66 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47atVZPuorXmoaa93v:-L47atVZPuorXmoaa93w:b-r3y7v) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L66)):*
> The ideal approach would be to use an exponential randomization distribution (Poisson Process) to ensure clients adequately spread out the intervals that tests start.

How about: 
The ideal approach would be to ensure that the test start times constitute a Poisson process (and are therefore memoryless); this can be done by choosing each inter-test wait time from an exponential distribution. In python, the appropriate function for this is `random.expovariate`, but similar functions are available in all major programming languages.

---

*[_pages/developers.md, line 85 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47bslg-4idf-ZCzp5D:-L47bslg-4idf-ZCzp5E:b90hfzx) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L85)):*
> ```Markdown
> ### Can I use M-Lab’s services without measurements being added to the public dataset?
> 
> No.
> ```

Perhaps:

No. The price of using M-Lab's test infrastructure and services is the sharing of the resulting data.

---

*[_pages/developers.md, line 99 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47cgBTYQMmXWAqosaO:-L47cgBTYQMmXWAqosaP:bgx0zjt) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L99)):*
> ```Markdown
> ### Can commercial or closed source services use M-Lab?
> 
> Yes.
> ```

Perhaps: 

Yes. Anyone may use M-Lab's services as long as they follow the AUP and obtain user consent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 27 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47dp1JHyBmnMG57BNk:-L47hjee1IfYi2gs2-bM:b9kwai3) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L27)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

The easiest and recommended way to deal with changing server availability is to use our directory service.
</blockquote></details>

Clarifying question: are you suggesting this sentence replace the three above it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 52 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47_shlycdHomofNyKe:-L47ikhFAvBbYBW7lQWK:b-j6o0zl) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L52)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

> Note that the user is not required to consent to this information being sent.

The mlab-ns logs are not governed by M-Lab's open-data policy. Queries to mlab-ns may be sent prior to acquiring user consent to run the actual test.
</blockquote></details>

Again, just to clarify, are you suggesting that these two sentences replace the one above it? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
Thanks @pboothe . I've added a commit to address your CR comments. Could you take another look?

**Comment by pboothe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[_pages/developers.md, line 27 at r1](https://beta.reviewable.io/reviews/m-lab/m-lab.github.io/345#-L47dp1JHyBmnMG57BNk:-L47vfBtBGMh67i1nWKc:b-twnrl0) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L27)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Clarifying question: are you suggesting this sentence replace the three above it?
</blockquote></details>

What you did is what I was trying to indicate.

---

*[_pages/developers.md, line 52 at r1](https://beta.reviewable.io/reviews/m-lab/m-lab.github.io/345#-L47_shlycdHomofNyKe:-L47_iSPxsO2gkPBEbku:b7ixb9l) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L52)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Again, just to clarify, are you suggesting that these two sentences replace the one above it? 
</blockquote></details>

I am suggesting that the text I gave should replace the one sentence "Note that the user is not required to consent to this information being sent." because that sentence sounded a little strange and potentially overbroad.

---

*[_pages/developers.md, line 65 at r2](https://beta.reviewable.io/reviews/m-lab/m-lab.github.io/345#-L47wTQXCuUakdMGBRvg:-L47wTQXCuUakdMGBRvh:b9jevig) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/f70243baface7a5422279092b7d7bbdc1bedaa6c/_pages/developers.md#L65)):*
> ```Markdown
> M-Lab welcomes automated and repeated testing. However, doing so requires user consent and care in implementation so that clients do not unintentionally overload the platform.
> 
> The M-Lab platform is well provisioned to handle a large amount of concurrent tests. In order to avoid potential site-reliability issues, we recommend that clients that perform automated testing take steps to spread the distribution of their clients’ tests evenly. It is often sufficient to randomize the times that tests are initiated. We also recommend that automatic and/or bandwidth intensive tests should not initiate more than two tests per hour to a server. The ideal approach would be to ensure that the test start times constitute a Poisson process (and are therefore memoryless); this can be done by choosing each inter-test wait time from an exponential distribution. In python, the appropriate function for this is random.expovariate, but similar functions are available in all major programming languages.
> ```

Please put backtics around random.expovariate to make it render like `random.expovariate`

---

*[_pages/developers.md, line 84 at r2](https://beta.reviewable.io/reviews/m-lab/m-lab.github.io/345#-L47wmon13HFLW-4heDo:-L47wmon13HFLW-4heDp:b-c77mk2) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/f70243baface7a5422279092b7d7bbdc1bedaa6c/_pages/developers.md#L84)):*
> ```Markdown
> ### Can I use M-Lab’s services without measurements being added to the public dataset?
> 
> No. Using M-Lab's test infrastructure and services requires the sharing of the resulting data.
> ```

The tense in this sentence is a little all over the place.  Maybe:

Using M-Lab's test infrastructure and services requires sharing the resulting data.

or maybe just back to "No." Unlike the "Yes." below, perhaps a flat "No." is appropriate here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 41 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47_LVxnAymZbn91aEf:-L485yxpqeoRRsPBWh8d:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L41)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Remove NPAD, add ndt_ssl. Nobody uses NPAD, and we are not planning on porting it forward.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 56 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47aVsWfGYba7PnBNrs:-L4866bQy7T9D56CNzLG:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L56)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

remove 'actual'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 84 at r2](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47wmon13HFLW-4heDo:-L4CNkFxSX6fwWP0I5Ow:b-v16eoh) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/f70243baface7a5422279092b7d7bbdc1bedaa6c/_pages/developers.md#L84)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

The tense in this sentence is a little all over the place.  Maybe:

Using M-Lab's test infrastructure and services requires sharing the resulting data.

or maybe just back to "No." Unlike the "Yes." below, perhaps a flat "No." is appropriate here.
</blockquote></details>

I think more than No is needed. I'm going to reference the statement on our data page:
"All data collected by M-Lab tests are available to the public without restriction under a [No Rights Reserved Creative Commons Zero Waiver](http://creativecommons.org/about/cc0)."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 99 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47cgBTYQMmXWAqosaO:-L4COSqSiREfZd9kRbQt:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L99)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Perhaps: 

Yes. Anyone may use M-Lab's services as long as they follow the AUP and obtain user consent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 84 at r2](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47wmon13HFLW-4heDo:-L4COTp5UNZt3HgaEX8v:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/f70243baface7a5422279092b7d7bbdc1bedaa6c/_pages/developers.md#L84)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I think more than No is needed. I'm going to reference the statement on our data page:
"All data collected by M-Lab tests are available to the public without restriction under a [No Rights Reserved Creative Commons Zero Waiver](http://creativecommons.org/about/cc0)."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 85 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47bslg-4idf-ZCzp5D:-L4COUwxpfFlB5e0E2Hm:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L85)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Perhaps:

No. The price of using M-Lab's test infrastructure and services is the sharing of the resulting data.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 65 at r2](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47wTQXCuUakdMGBRvg:-L4COW4-NiMGMedNIdoR:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/f70243baface7a5422279092b7d7bbdc1bedaa6c/_pages/developers.md#L65)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please put backtics around random.expovariate to make it render like `random.expovariate`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 66 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47atVZPuorXmoaa93v:-L4COXLHzYVeDj5E6xx2:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L66)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

> The ideal approach would be to use an exponential randomization distribution (Poisson Process) to ensure clients adequately spread out the intervals that tests start.

How about: 
The ideal approach would be to ensure that the test start times constitute a Poisson process (and are therefore memoryless); this can be done by choosing each inter-test wait time from an exponential distribution. In python, the appropriate function for this is `random.expovariate`, but similar functions are available in all major programming languages.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 52 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47aKX9a4DVGwOM4WxQ:-L4COYnmdnQdyYQLlUNN:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L52)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

> Finally, using this information ...

Using the location from AppEngine, ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by critzo** [comment]
*[_pages/developers.md, line 52 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-L47_shlycdHomofNyKe:-L4COZaasqw1PC0x2LvE:b-896fix) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3b5d67166e7b523ede15c28065e5f446d9b475c6/_pages/developers.md#L52)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I am suggesting that the text I gave should replace the one sentence "Note that the user is not required to consent to this information being sent." because that sentence sounded a little strange and potentially overbroad.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345)*

**Comment by pboothe** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/345#-:-L4D9wVEWTHXusf-mqWP:bnfp4nl)*

**Comment by critzo** [comment]
@georgiamoon In the latest commit, the developer guide is in the Contribute section, per our discussion. Again, live preview is not available unless you build locally for this branch. Screen shot of the Contribute page:

contribute

**Pull request merged**
