### PR TITLE
Adding visible anchor permalinks to headers that have IDs

### PR DESCRIPTION
**Pull request by shredtechular**
This PR adds visible (GitHub-like) anchor permalinks to H tags that have IDs in the main content sections of the site.  This functionality can be see on my [fork](http://shredtechular.github.io/m-lab.github.io/), and please pay particular attention to the blog permalinks.  

- [x] The solution uses a small javascript snippet that will add the anchor link to any header that has an ID.

- [x] CSS will do the rest of the magic that makes the link visible when hovering over one of the headers that has an anchor link.

- [ ] Notice this PR doesn't update the permalink to the full blog post URL, it only appends the header IDs to it.  Therefore, I don't think this fully solves the blog permalink issue.  We can either 
  a. do a simple URL substitution on the blog index page & blog archive page within the permalink anchors to point to the actual blog post URL, 
  b. or we can remove the permalinks within blog posts altogether (as I don't think I see that too much in blog posts?) and simply let the user know the "permalink" maybe next to or underneath the title,
  c. or we can simply link the titles within the blog landing pages & archive pages to the actual blog post.

- [ ] Finally, the CSS is currently using an icomoon font type, however, when we move to bootstrap, I recommend using bootstrap's glyphicons for this, so that piece is only temporary until bootstrap is incorporated.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/137)

### CODE REVIEW

**Comment by mtlynch** [comment]
Haven't reviewed the code, but just wanted to pop in and say that I **love** this functionality:

image

**Comment by georgiamoon** [comment]
Agreed! And it's everywhere in the site! <3 <3 <3

On Thu, Mar 31, 2016 at 3:27 PM, Michael Lynch <notifications@github.com>
wrote:

> Haven't reviewed the code, but just wanted to pop in and say that I *love*
> this functionality:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7783288/14188227/1b8bfa20-f755-11e5-9558-0e999fb1fc93.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/m-lab/m-lab.github.io/pull/137#issuecomment-204089790>
>



-- 
Georgia Bullen
Director of Technology Projects
Open Technology Institute <http://newamerica.org/oti/> @ New America
<http://newamerica.org>
740 15th Street NW, Suite 900, Washington DC, 20005
@georgiamoon <http://twitter.com/georgiamoon>

**Comment by critzo** [comment]
:lgtm: @shredtechular 
Love it. I think on the question of blog permalinks, you're right, this PR doesn't address what we want, but that can be done in a different PR. Let's add this, move on to the responsiveness, then return to the blog permalink feature later.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/137#-:-KEDLMlTJszf8Gjo6zHG:614673762)*

**Comment by critzo** [comment]
Awesome. Let's save the blog permalinks for after the responsive mobile design.

**Pull request merged**
