### PR TITLE
Update site pages with copy-edited and reviewed content

### PR DESCRIPTION
**Pull request by critzo**
This PR is rather large, but solely focuses on updating content that has been edited by our copy editor contractor and reviewed by M-Lab staff. In some cases a template file or include file was edited to update content drawn in from those sources, such as the footer or grid of tests on the tests page. 

This PR can be previewed on my [fork](https://critzo.github.io/m-lab.github.io/) and should fulfill the requirements to close issues #162 #163 #129 #130 and #131

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/187)

### CODE REVIEW

**Comment by georgiamoon** [comment]
*[_data/header-footer-content.yml, line 94 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0KH8Arve05F9bfC4:-KGK0KH9glGoqIsRSqC_:1567270540) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_data/header-footer-content.yml#L94)):*
Why do we reference New America here at all? Do we have to? Seems strange.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/08-about.md, line 10 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0Zt5iu6Y6btAAikx:-KGK0Zt6mzus5iumZvfk:-713705760) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/08-about.md#L10)):*
I would remove the M-Lab from here, and just leave "Open Internet Measurement"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/08-about.md, line 17 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0f2Xw1tpCErAR-Pe:-KGK0f2Xw1tpCErAR-Pf:-698011716) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/08-about.md#L17)):*
This is the only bullet ending in a period. Either end each of them with it, or remove the period at the end of the sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_includes/grid.html, line 32 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0wv_eg44qk4fcRN3:-KGK0wv_eg44qk4fcRN4:1811008361) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_includes/grid.html#L32)):*
Does this change belong in this PR? Seems like it's not a content change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_layouts/page.html, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK17RyzecaFQ9PZmiH:-KGK17RyzecaFQ9PZmiI:115880651) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_layouts/page.html#L14)):*
similarly, this page is showing as edited, even though it wasn't. Can we discard changes on this file? so that it's not included in the PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/contact.md, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK288BZdXPQxE_qiIQ:-KGK288CEqdyITkqwgqA:-852639496) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/contact.md#L14)):*
I don't think the %21 change should be in here. @mtlynch can you double check me here? Both links work, but I'd think we'd want '#!forum' and not using %21 in the link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/faq.md, line 64 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK2WVCn57pQLMhfNB2:-KGK2WVCn57pQLMhfNB3:1633889976) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/faq.md#L64)):*
This change got reverted, and should be discarded. I think this is a rebase/version issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
Left some comments to address, which should be small. PTAL?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-:-KGN7OE61rEEihqTCRbp:813706305)*

**Comment by mtlynch** [comment]
Reviewed 4 of 30 files at r1.
Review status: 4 of 31 files reviewed at latest revision, 11 unresolved discussions.

---

*[_pages/bigquery_examples.md, line 38 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNmKMMv61uU-0nvH-W:-KGNmKMMv61uU-0nvH-X:-600035402) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/bigquery_examples.md#L38)):*
Why are we taking out the backticks for code?

---

*[_pages/contact.md, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK288BZdXPQxE_qiIQ:-KGNomuq8BW0SFVmxfhZ:-2075384757) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/contact.md#L14)):*
Yeah, I'd prefer the unencoded exclamation point. I don't think any browsers will choke on it.

---

*[_pages/gcs.md, line 91 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNmrnoHr9MvG9S2CkJ:-KGNmrnoHr9MvG9S2CkK:135023324) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/gcs.md#L91)):*
The trailing `b` was correct.

If it makes it seem less accidental, we can do 

>You can access M-Lab files programmatically by replacing:
 
>`storage.cloud.google.com/m/cloudstorage/b/`
 
>with
 
>`storage.googleapis.com/`

---

*[_pages/gcs.md, line 111 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNnK72Lrxkjae0wYei:-KGNnK72Lrxkjae0wYej:2050653183) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/gcs.md#L111)):*
This looks like a mistake

---

*[_pages/tools/glasnost.md, line 10 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNnccgKdJwasiq5IYc:-KGNnccgKdJwasiq5IYd:-1137935811) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/tools/glasnost.md#L10)):*
Can we cut the mention of eMule and Gnutella? I don't think anyone has used those in like 10 years.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_data/header-footer-content.yml, line 94 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0KH8Arve05F9bfC4:-KGO74rrdl78yQKcAe7x:-88677925) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_data/header-footer-content.yml#L94)):*
This is just what was on the old site. New America reference could be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_data/header-footer-content.yml, line 94 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0KH8Arve05F9bfC4:-KGO7OU0KHFMFrxrlgAg:871987718) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_data/header-footer-content.yml#L94)):*
I'll remove this in my next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_includes/grid.html, line 32 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0wv_eg44qk4fcRN3:-KGO7X0SeZkom2H4S9Jh:1551336799) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_includes/grid.html#L32)):*
This change is for the /tests/ page, moving the descriptions of test categories from the top of the page to below the heading for that category. The content for the grid of tests on the tests page is in the YAML front matter and grid.html puts the page together on build. I added an additional value to the YAML called group-description, and this template pulls that in when it creates the page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/bigquery_examples.md, line 38 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNmKMMv61uU-0nvH-W:-KGOB8T1tSlEcyOr4FSU:-128674431) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/bigquery_examples.md#L38)):*
I didn't catch those. Our copy editor went a bit overboard on this page and removed them, so I had to add them back in. I missed these. Will add back in my next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by mtlynch** [comment]
It seems that there are a number of style conventions we've begun to follow, regarding capitalization of headers, "data sets" instead of "datasets". Can we add a section to the readme.md or maybe a file called style_guide.md that documents these patterns? Maybe we can even add automated tests to enforce these style choices. It seems doable to make a check that flags instances of the word "dataset" if someone accidentally introduces it in the future.

---

Reviewed 13 of 30 files at r1, 1 of 3 files at r2, 6 of 8 files at r3.
Review status: 21 of 30 files reviewed at latest revision, 13 unresolved discussions.

---

*[_pages/02-visualizations.md, line 3 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmAEYrqTUVrzq5lku:-KGOmAEYrqTUVrzq5lkv:-1418609961) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/02-visualizations.md#L3)):*
Suggest cutting the visualizations page (and all subpages) entirely at this point. Or at least taking it out of main navigation. Everything is so out of date and we keep burning cycles dragging it forward.

---

*[_pages/03-tests.md, line 81 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmh5fY5BJCzH2OTq4:-KGOmh5gNHMfrlI9Gs2W:571159535) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/03-tests.md#L81)):*
Did the `--` (in "run them--") come from the copy editor? That seems unusual style and I don't see it anywhere else on the page.

---

*[_pages/05-contribute.md, line 34 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOnEz4JFoaVu8oCdAB:-KGOnEz5lrkIYgaafUIw:-2089228770) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/05-contribute.md#L34)):*
Why aren't the headings on this page capitalized like the others? Is it a matter of header level?

---

*[_pages/state.md, line 79 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOkN0wmkE0R0kJq5gC:-KGOkN0xG8oXT-22aIx3:2016944229) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/state.md#L79)):*
If we're capitalizing headings, shouldn't "Tests" be capitalized?

---

*[_pages/tools/neubot.md, line 10 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOlIgIAj90_WMuIxcy:-KGOlIgJn4SmnHsOoD3a:-1589373954) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/tools/neubot.md#L10)):*
Looks like we're missing the trailing double quote on `"bittorrent`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-:-KGOoIPKLqUcoY1FtnXl:1882541818)*

**Comment by georgiamoon** [comment]
*[_pages/02-visualizations.md, line 3 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmAEYrqTUVrzq5lku:-KGUom67eDUd4wzULyL1:1856631694) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/02-visualizations.md#L3)):*
Let's add an issue to address this page at the moment, but I'd prefer to *not* remove the page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/03-tests.md, line 81 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmh5fY5BJCzH2OTq4:-KGUp382jYWTLQbrXq0G:1136059828) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/03-tests.md#L81)):*
True -- @critzo can you check this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/05-contribute.md, line 34 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOnEz4JFoaVu8oCdAB:-KGUpepP-7hBGzuexucq:-1914450868) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/05-contribute.md#L34)):*
@critzo did you check these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/contact.md, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK288BZdXPQxE_qiIQ:-KGUq_OglJjwy18R5ARH:-347537180) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/contact.md#L14)):*
@critzo it needs the '#!forum' -- the link is broken at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/state.md, line 79 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOkN0wmkE0R0kJq5gC:-KGUrBKYcKx-r4xSfuA9:1252894816) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/state.md#L79)):*
@critzo another quick one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_pages/tools/neubot.md, line 10 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOlIgIAj90_WMuIxcy:-KGUrkaKWaRIk64_OA1N:1431549662) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/tools/neubot.md#L10)):*
@critzo another quick edit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
*[_layouts/page.html, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK17RyzecaFQ9PZmiH:-KGUt0SxgkY0r909s-Iw:-342976246) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_layouts/page.html#L14)):*
This is still showing some weird edits. Were you able to discard the changes here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_data/header-footer-content.yml, line 94 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0KH8Arve05F9bfC4:-KGXYgvOmGDpvmDajRNg:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_data/header-footer-content.yml#L94)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_data/header-footer-content.yml, line 94 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0KH8Arve05F9bfC4:-KGXYgvOmGDpvmDajRNg:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_data/header-footer-content.yml#L94)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/03-tests.md, line 81 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmh5fY5BJCzH2OTq4:-KGX_6KMz_OiKfLAPAdh:-1729243085) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/03-tests.md#L81)):*
@georgiamoon @mtlynch I reviewed the Google doc revision history and it looks like this was mistakenly added during our review after the copy editor's pass. Suggested revision: 
This means that tests only run when people decide to run them. They do not passively monitor your connection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/05-contribute.md, line 34 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOnEz4JFoaVu8oCdAB:-KGXa2W922exjBOycTKS:-2078590648) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/05-contribute.md#L34)):*
@georgiamoon I will check them again. To @mtlynch 's comments elsewhere about style guide, our copy editor provided a mix of capitalizing words in headings and not. What is our preference for capitalization in headings? Based on your reply I will review all the pages again for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/02-visualizations.md, line 3 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmAEYrqTUVrzq5lku:-KGXaee_QQheUk6hqHfQ:1885606034) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/02-visualizations.md#L3)):*
Logged as an issue in https://github.com/m-lab/m-lab.github.io/issues/189

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/08-about.md, line 10 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0Zt5iu6Y6btAAikx:-KGXanOMKcqU1SBGQaJu:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/08-about.md#L10)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/08-about.md, line 17 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK0f2Xw1tpCErAR-Pe:-KGXaqGfwpfEC0w7DP0P:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/08-about.md#L17)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/bigquery_examples.md, line 38 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNmKMMv61uU-0nvH-W:-KGXatTSauTmbG-nhKFH:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/bigquery_examples.md#L38)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/contact.md, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK288BZdXPQxE_qiIQ:-KGXb30qNv52_BWLNsTw:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/contact.md#L14)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/faq.md, line 64 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK2WVCn57pQLMhfNB2:-KGXb7FMQe0ynfhgdDqe:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/faq.md#L64)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/gcs.md, line 111 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGNnK72Lrxkjae0wYei:-KGXbAISgPYES_VQyJlj:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_pages/gcs.md#L111)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/state.md, line 79 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOkN0wmkE0R0kJq5gC:-KGXbE5svC63AKu8dx_N:2127192300) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/state.md#L79)):*
@georgiamoon @mtlynch looks like our preference is for capitalizing. I'll review all pages for this and capitalizing words in headings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/tools/neubot.md, line 10 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOlIgIAj90_WMuIxcy:-KGXc1bUYHDGk9Bwzhxg:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/tools/neubot.md#L10)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_layouts/page.html, line 14 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGK17RyzecaFQ9PZmiH:-KGXdF-GNI5BpLdTvhBr:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/3f4e6078aefe47bc7f1e20f3617157da9b81db81/_layouts/page.html#L14)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/03-tests.md, line 81 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOmh5fY5BJCzH2OTq4:-KGY8YOt0P0R9XSEybvV:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/03-tests.md#L81)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/05-contribute.md, line 34 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOnEz4JFoaVu8oCdAB:-KGYBCQa0kk2bkJ7RB0w:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/05-contribute.md#L34)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by critzo** [comment]
*[_pages/state.md, line 79 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-KGOkN0wmkE0R0kJq5gC:-KGYBFEwkYA-G-tmtn_M:-499146009) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/dd20a8ce04e536d98a17cfad982da0fe070f2c24/_pages/state.md#L79)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Comment by georgiamoon** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187#-:-KGYEHCyvEVTx-ZTkIJp:1417088721)*

**Comment by georgiamoon** [comment]
Reviewed 18 of 30 files at r1, 1 of 3 files at r2, 6 of 8 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/187)*

**Pull request merged**
