### PR TITLE
Update FAQ content after final review.

### PR DESCRIPTION
**Pull request by critzo**
External copy editor's comments and edits have been addressed in this PR. Note that this PR also contains minor edits to the contribute page, residue from a previous PR that was closed regarding content on that page. A new PR will be issued for the contribute page and other content.

Content can be previewed on my fork:
https://critzo.github.io/m-lab.github.io/faq/

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/165)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[_pages/faq.md, line 47 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-KErVJm0fPZNMOcomHPk:-KErVJm0fPZNMOcomHPl:1937507042) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a80118cfaef42201386691f6d2cc73699b61b4f8/_pages/faq.md#L47)):*
Can we consistently use `{{ site.baseurl }}` instead of `measurementlab.net`? It otherwise messes up links in the non-prod versions of the site.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165)*

**Comment by critzo** [comment]
Whoops. Will correct now. Gdocs content review fail.

 Chris Ritzo
 Senior Technologist, Open Technology Institute @ New America
 740 15th Street NW, Suite 900
 Washington, DC 20036
 Public Key:    0x085B309C

**Comment by critzo** [comment]
@mtlynch Updated internal links to use site.baseurl 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-:-KEr_Nx0LNBmtzjAzmuw:1151149492)*

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[_pages/faq.md, line 45 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-KEraczZmnAkC46MScGF:-KEraczZmnAkC46MScGG:177639536) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/eb153fd1dec24da6f6e978a796779c5a24b0d11b/_pages/faq.md#L45)):*
Looks like stray untemplated URL got left behind

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165)*

**Comment by critzo** [comment]
*[_pages/faq.md, line 45 \[r2\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-KEraczZmnAkC46MScGF:-KErc2nXl0VP9DyTXHFI:-2001214806) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/eb153fd1dec24da6f6e978a796779c5a24b0d11b/_pages/faq.md#L45)):*
Thanks for catching that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165)*

**Comment by georgiamoon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[_pages/faq.md, line 35 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-KEretjTL8dd6dNyvRwH:-KEretjURqKh9FML6Hti:-724956748) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/02f588c66cc1c2790c9522a119db6579c0dde796/_pages/faq.md#L35)):*
the ``` * ``` for italics is before the comma, and should probably be after, so that it's on the words, not the punctuation.

---

*[_pages/faq.md, line 65 \[r3\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-KEreg0eStXpcIiRdWke:-KEreg0fkHo8HKQDkLBj:-1608848300) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/02f588c66cc1c2790c9522a119db6579c0dde796/_pages/faq.md#L65)):*
How we are using emphasis is inconsistent here -- ``` * word * : ```  vs ``` * word : * ```

Let's be consistent for a clean look and put it after the colon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165)*

**Comment by georgiamoon** [comment]
:lgtm: with some last tiny edits!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/165#-:-KErgWz97ETMNfqvlh8L:-817590097)*

**Pull request merged**
