### PR TITLE
Add ETL post, update related docs

### PR DESCRIPTION
**Pull request by critzo**
This PR adds a blog post and associated pages. We're waiting to merge until the data processing is completed, but I wanted to start this review in advance to be as timely as we can.

This PR is reviewable on my fork: https://critzo.github.io/m-lab.github.io/

@gfr10598 if you could PTAL, focusing on the queries and query documentation, as well as the post. 
@georgiamoon or @pboothe if you could review as well?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/344)

### CODE REVIEW

**Comment by gfr10598** [comment]
Reviewed 3 of 11 files at r1.
Review status: 3 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[_pages/bigquery_schema.md, line 17 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47tTL6axmp8P0sOgUs:-L47tTL6axmp8P0sOgUt:b-r7kfvz) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L17)):*
> ```Markdown
> * For each test, a server collects a **log**, and the test can be uniquely identified by its log filename.
> 
> ## BigQuery Storage and Processing Datasets
> ```

Does this convey the right thing?  No better word is occurring to me, but I'm not quite sure what distinction you are trying to make.

"Base and Intermediate Datasets" ?
I'm thinking of these as something like:
This group contains lower level groupings of the data.  These allow us to keep different blocks of data in slightly differing native schema, prevent preliminary data separate from fully baked data, (e.g., for data that has a lot of duplicate rows), and keep temporary changes in implementation details from impacting users.

---

*[_pages/bigquery_schema.md, line 30 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vFNxwdTcRrhtBvZa:-L47vFNxwdTcRrhtBvZb:bkqpxpi) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L30)):*
> ```Markdown
>   * Destination for batch processed data prior to dedupping.
> 
> * **intermediate_vX_X_X**
> ```

Nit: Slight preference for intermediate_vX_Y_Z

---

*[_pages/bigquery_schema.md, line 36 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vMb26lfyjLD3RwsI:-L47vMb26lfyjLD3RwsJ:b787irq) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L36)):*
> ```Markdown
> 
> * **legacy**
>   * Contains exact copies of the data stored in our previous project tables, for use in the intermediate and release views.
> ```

previous NDT fast tables, (pre 2017 plx tables)

We should probably copy the legacy SS and PT tables too?

---

*[_pages/bigquery_schema.md, line 38 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vXSDhWLHCHytY0NL:-L47vXSDhWLHCHytY0NM:b-csjfod) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L38)):*
> ```Markdown
>   * Contains exact copies of the data stored in our previous project tables, for use in the intermediate and release views.
> 
> ## Recommended Datasets for Most Researcher Queries
> ```

How about:
Working Views for Most Researcher Queries.

---

*[_pages/bigquery_schema.md, line 42 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vgoVDTBsaRCmjYCJ:-L47vgoVDTBsaRCmjYCK:b-ap4ozf) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L42)):*
> ```Markdown
> The datasets in the previous section outline where raw M-Lab test data is parsed and stored. While they are also queryable in the above locations, M-Lab recommends that most researchers instead begin querying the views published in our **release** dataset. This will make future table schema transitions less impactful since queries can be pinned to the release views instead of to a specific table name.
> 
> Three _researcher query datasets_ are published for each new release:
> ```

Is it worth spelling out that rc_vX_X is attached to a specific release, but rc is a moving target, pointing at the next release candidate, and release is the latest stable release, not any specific release?

---

*[_pages/bigquery_schema.md, line 71 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47w1jOI0ClJaGuP7Hy:-L47w1jOI0ClJaGuP7Hz:bey3ugc) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L71)):*
> ```Markdown
> * **base_tables**
>   * ndt - `measurement-lab.base_tables.ndt`
>   * sidestream - `measurement-lab.base_tables.sidestream`
> ```

Note that ss and pt are not yet ported to base_tables, and also don't have consolidated views yet.  My focus has been to make all this work for NDT, and we need to work out who will create the SS and PT views, and eventually move the daily pipeline output to base_tables.

---

*[_pages/bigquery_schema.md, line 78 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47wgSWQJpaOZ9-jM0H:-L47wgSWQJpaOZ9-jM0I:btpvs5o) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L78)):*
> ```Markdown
> The current version of M-Lab BigQuery tables is v3.1, and are listed below. Tables are **bolded** and table views are listed underneath where applicable.
> 
> ### Historical Data and Current Data Base Tables
> ```

Is this intended to sound like database tables, or data base_tables?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by gfr10598** [comment]
Review status: 3 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[_pages/fast_tables_migration.md, line 49 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47xZ47j8o7qyxy1vbj:-L47xZ47j8o7qyxy1vbk:b-ev4j57) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/fast_tables_migration.md#L49)):*
> ```Markdown
> If your queries are for Sidestream and Paris Traceroute data, please use the following tables:
> 
> * `measurement-lab:base_tables.sidestream`
> ```

These don't exist yet.  We should mention that they are coming, but that in the mean time people should keep using the plx tables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
Reopening this PR to add the ETL post and associated changes. This PR was inadvertently closed when I accidentally overwrote my local master and pushed to my fork's remote. This commit re-adds the changes from the original PR.

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 17 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47tTL6axmp8P0sOgUs:-L4mZohMki8SQ1y9Co5l:b-u1xsr) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L17)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Does this convey the right thing?  No better word is occurring to me, but I'm not quite sure what distinction you are trying to make.

"Base and Intermediate Datasets" ?
I'm thinking of these as something like:
This group contains lower level groupings of the data.  These allow us to keep different blocks of data in slightly differing native schema, prevent preliminary data separate from fully baked data, (e.g., for data that has a lot of duplicate rows), and keep temporary changes in implementation details from impacting users.

</blockquote></details>

I think this communicates what these are used for functionally. Open to suggestion, but Base and Intermediate doesn't seem right to me. I'm not sure the description is necessary. Might confuse people.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 30 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vFNxwdTcRrhtBvZa:-L4m_VjCZrM4VNsiiurq:bni5p4p) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L30)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Nit: Slight preference for intermediate_vX_Y_Z
</blockquote></details>

Changed to this preference wherever it's referenced.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 36 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vMb26lfyjLD3RwsI:-L4m_cXK9IMfE24ckLd6:b-s9spfw) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L36)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

previous NDT fast tables, (pre 2017 plx tables)

We should probably copy the legacy SS and PT tables too?
</blockquote></details>

Defer to you all for the plan on legacy SS and PT tables. At the very least I think we should prioritize getting PT and SS tables into base_tables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 38 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vXSDhWLHCHytY0NL:-L4m_wsMQa_mwPeYPuxr:byub911) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L38)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How about:
Working Views for Most Researcher Queries.
</blockquote></details>

I don't think that change would add any clarification. Datasets is the right word here in my opinion because we are listing three datasets, each containing Views. If anything we could make this "Recommended Datasets and Views for Most Researcher Queries"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 42 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vgoVDTBsaRCmjYCJ:-L4mb1eFRFXecaKPcHdt:bf5szn) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L42)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is it worth spelling out that rc_vX_X is attached to a specific release, but rc is a moving target, pointing at the next release candidate, and release is the latest stable release, not any specific release?
</blockquote></details>

The first bullet under rc addresses the moving target issue. I'll add some test to the release_X_Y_Z bullet for additional clarity in my next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 71 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47w1jOI0ClJaGuP7Hy:-L4h04yicLzFNfuVJ2Y4:b3i6mtr) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L71)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Note that ss and pt are not yet ported to base_tables, and also don't have consolidated views yet.  My focus has been to make all this work for NDT, and we need to work out who will create the SS and PT views, and eventually move the daily pipeline output to base_tables.
</blockquote></details>

Added text to make it clear that SS and PR tables/views are coming soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/bigquery_schema.md, line 78 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47wgSWQJpaOZ9-jM0H:-L4mcq9ye2wrljITzWAK:bpxcc8z) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L78)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this intended to sound like database tables, or data base_tables?  
</blockquote></details>

changed to "Base Tables for Historical and Current Data"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
*[_pages/fast_tables_migration.md, line 49 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47xZ47j8o7qyxy1vbj:-L4h8zsE0k1qBMKy04Yu:bb7cwne) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/fast_tables_migration.md#L49)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

These don't exist yet.  We should mention that they are coming, but that in the mean time people should keep using the plx tables.
</blockquote></details>

ack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344)*

**Comment by critzo** [comment]
@gfr10598 @georgiamoon I've just reissued this PR after losing a bit of work and having to re-commit it. In any case, I've attempted to address many of the initial review comments and look forward to your second round review. Thanks.

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 1 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[_pages/bigquery_schema.md, line 38 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47vXSDhWLHCHytY0NL:-L4qNwqi_-bE6aG_2MDX:bki6awc) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L38)):*
> Recommended Datasets and Views for Most Researcher Queries
I like this suggestion

---

*[_pages/bigquery_schema.md, line 71 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47w1jOI0ClJaGuP7Hy:-L4qOuu7EvvRlBe86q6h:b-ucfkn4) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L71)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Added text to make it clear that SS and PR tables/views are coming soon.
</blockquote></details>

Thanks.

---

*[_pages/bigquery_schema.md, line 78 at r1](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-L47wgSWQJpaOZ9-jM0H:-L4qPBh8xt2ywTZJmOzb:btojbfd) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/a665c04c1d59ffbd9dc439cc84edeb715fe03b21/_pages/bigquery_schema.md#L78)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

changed to "Base Tables for Historical and Current Data"
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/344#-:-L4qQ4YN5klhlL3AIcNk:bnfp4nl)*

**Comment by critzo** [comment]
Thanks @gfr10598 ! 
@pboothe you have the baton. Look forward to your review.

**Comment by pboothe** [comment]
LGTM

**Pull request merged**
