### PR TITLE
Add PT remediation post, correct title from Oct blog date index

### PR DESCRIPTION
**Pull request by critzo**
This PR adds a follow up post to the PT bug post we have from earlier this year.
Content is reviewable here: http://35.208.161.188/

@pboothe , @yachang or @georgiamoon PTAL when you have a moment?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/409)

### CODE REVIEW

**Comment by georgiamoon** [comment]
___
*[_posts/blog/2018-11-09-pt-bug-remediation.md, line 3 at r1](https://reviewable.io/reviews/m-lab/m-lab.github.io/409#-LRCXbFI19gRRVsut4T_:-LRCXbFI19gRRVsut4Ta:b-5sgjrc) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/1ab4e7ac64176c2127ea4e36f06a82248e6dcf84/_posts/blog/2018-11-09-pt-bug-remediation.md#L3)):*
Suggested change:
> Update: Paris Traceroute Bug from Early 2018

**Comment by georgiamoon** [comment]
___
*[_posts/blog/2018-11-09-pt-bug-remediation.md, line 13 at r1](https://reviewable.io/reviews/m-lab/m-lab.github.io/409#-LRCYGYBAXGxJ3maBFj_:-LRCYGYBAXGxJ3maBFja:b92no89) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/1ab4e7ac64176c2127ea4e36f06a82248e6dcf84/_posts/blog/2018-11-09-pt-bug-remediation.md#L13)):*
> ```Markdown
> ---
> 
> In December 2017, M-Lab was notified of oddities in the Paris Traceroute data. Upon investigation, a bug in the Paris Traceroute code was identified. The bug caused bad measurement data in 2.7% of the traceroutes since July 2016.
> ```

Maybe make a note and reference the post from January 2018 here? And note that there's overlap with that post, but we're including the detail here for clarity?

**Comment by georgiamoon** [comment]
___
*[_posts/blog/2018-11-09-pt-bug-remediation.md, line 25 at r1](https://reviewable.io/reviews/m-lab/m-lab.github.io/409#-LRCYbv72loWmD-J5xKw:-LRCYbv72loWmD-J5xKx:blgebm5) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/1ab4e7ac64176c2127ea4e36f06a82248e6dcf84/_posts/blog/2018-11-09-pt-bug-remediation.md#L25)):*
> ```Markdown
> The developers of Paris Traceroute reached out to us after our initial disclosure and created a version with that one bug fixed which can be found in the [master 2 branch in the official repository](https://github.com/libparistraceroute/libparistraceroute/tree/master2){:target="_blank"}. We are in the process of upgrading all our systems to this new version of Paris Traceroute.
> 
> Through disclosures and analyses like these, M-Lab re-confirms its commitment to open data and open science. Our raw data, warts, bugs, and all, is and will be always [available](https://console.google.com/storage/browser/archive-measurement-lab/){:target="_blank"}, while our processed data (https://bigquery.cloud.google.com/dataset/measurement-lab:release) continues to reflect our best understanding of the state of the Internet represented by that raw data.
> ```

The bigquery link here needs to be in markdown.

**Comment by georgiamoon** [comment]
Some comments/fixes, and then I think this is good to go.

**Comment by critzo** [comment]
Thanks @georgiamoon I've added a commit to address the comments and updated the preview site. PTAL?

**Comment by pboothe** [comment]
LGTM

**Pull request merged**
