### PR TITLE
NDT HTML5 test Embeddable IFRAME fixes

### PR DESCRIPTION
**Pull request by shredtechular**
This PR is a stab at remedying issue #92 .  These fixes can be previewed on my [fork](http://shredtechular.github.io/m-lab.github.io/tools/ndt/).

> - Make the widget self-contained so that it has M-Lab's logo and a link back to M-Lab's site and brief
>   text explaining that it's a bandwidth test. It shouldn't require surrounding context of the page to explain
>   what the widget is.

- [x]  The M-Lab logo is now incorporated into the widget and displays throughout the test.  Also, took a stab at the brief text explaining the bandwidth test (this probably needs **strict review** to make sure that verbage fits and is what was desired.  I didn't remove any other content from the NDT TEST page, but that can certainly be done if folks felt like it wasn't useful.  I thought it was okay to leave in there.  And it looked like that exact text used to exist in the widget as well.

> - Add a button to the widget that generates the HTML required for embedding

- [x] Added functionality where a user can select the iframe text and copy it for use in a user's own website.  
    - If folks are looking for a separate "wizard" type of generator for the widget where a user could customize the widget some, then I think that should exist outside of the widget.  This is something that could live on the first screen of the widget I think.    
    - For now I added all html & js changes into files controlled in the M-Lab website, however, I do wonder if all of the js can be moved to the NDT widget repo.  I think it would be good to get folks buy-in on everything before doing other PRs against those repos.
    - The copy functionality was tested on FF, Chrome, and Safari.  For browsers, like Safari, that don't support the copy functionality a fallback was implemented.  A couple screen caps to show that are below:

##### Copy Success:
screen shot 2016-04-25 at 11 17 05 am

##### Copy Failure:
screen shot 2016-04-25 at 11 17 52 am

> - The client currently generates a JS warning: Synchronous XMLHttpRequest on the main thread is
      deprecated because of its detrimental effects to the end user's experience. For more help, check
      https://xhr.spec.whatwg.org/. It's likely that mlab-ns isn't going to delay the page load much, but it'd
      be nice to avoid this. I think we can build more intelligence into the widget so that it the widget
      handles waiting for the mlab-ns response. 

- [x] Not sure if this is the solution desired, but also fixed this js warning by removing the ``async: false`` on the ajax call and only showing the "start test" screen if the ajax call is successful.  If for some reason the m-lab servers are not up, overburdened, or some other reason unreachable, then the below error message will be displayed to the end user.  Certainly will want **strict review** on this content too if this is in the ballpark of what folks were thinking to solve the asynchronous issue.
screen shot 2016-04-25 at 11 18 36 am

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/111)

### CODE REVIEW

**Comment by critzo** [comment]
*[_layouts/ndt-test.html, line 40 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdDBTu--LaNj1QLD3j:-KDdDBTv_3m2Wh1f9HG9:1728006526) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/e55599b70a5947ad2c58ac3738542f5ca5d8dde7/_layouts/ndt-test.html#L40)):*
@nkinkade @mtlynch We'll need your input on whether it's acceptable to remove this code for the widget

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by critzo** [comment]
*[_layouts/ndt-test.html, line 106 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdD_dVTdCbzIMhGgPj:-KDdD_dVTdCbzIMhGgPk:1178121482) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L106)):*
@georgiamoon @salarcon @mtlynch @nkinkade
We want this text to be reviewed broadly.  If you could take a look that would be great.

My suggested revised text:

Oops!! Something went wrong. There was a network connectivity issue preventing the NDT test from loading in your browser.

Please try to run the test again by clicking the Try Again button.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by critzo** [comment]
@shredtechular 
I added some comments for others to review text. @mtlynch @georgiamoon @salarcon215 @nkinkade Could you also review this PR?

I tested embedding and it works well. One question I had was that the M-Lab logo and the introductory text that you added "The NDT (Network Diagnostic Tool) is a bandwidth test that ... Begin Network Diagnostics" does not get included in the copy/pasted iFrame. I think we'd want that.

There is an interest in a wizard that customizes things like text, color, logo etc, but also still includes the M-Lab logo somewhere and a link back to us. 

You also mentioned wanting to move the html and js into the widget repo. I think that makes sense, but am curious what others think as well.

**Comment by georgiamoon** [comment]
*[_layouts/ndt-test.html, line 106 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdD_dVTdCbzIMhGgPj:-KDdH4zpw1M4VKRxIrFQ:533756289) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L106)):*
My suggested revision:
> Oops! Something went wrong and the NDT test didn't load!

> Please [Try Again].

> If this continues to happen, please contact support@measurementlab.net.

With the "Try Again" being the button.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by mtlynch** [comment]
>For now I added all html & js changes into files controlled in the M-Lab website, however, I do wonder if all of the js can be moved to the NDT widget repo. I think it would be good to get folks buy-in on everything before doing other PRs against those repos.

We don't have a widget repo yet. We have the [NDT repo](https://github.com/ndt-project/ndt/tree/master/HTML5-frontend), but the ultimate goal there is to remove all UI logic, so it should have no knowledge of any widgets. Process I had in mind was:

1. Make M-Lab's NDT widget embeddable
1. Smooth out separation between NDT repo and m-lab.github.io repo so that NDT repo doesn't have knowledge of UI
1. Extract the widget code we have in m-lab.github.io to create a standalone widget that others can fork and customize

Other thoughts on the UI (wait for @georgiamoon or @critzo for authoritative decisions here as I should not be trusted with UI decisions):

1. The "embed" UI feature should be WAY smaller. Like 1% of users will be interested in embedding this widget on a site, so suggest making it just a small button labeled "Embed" then then it pops more UI explaining how to do it when the user actually clicks it
1. Suggest "Begin Speed Test" rather than "Begin Network Diagnostics"
1. Consider a 1px border around the widget. I have trouble understanding where the page ends and the widget begins, so I actually didn't notice the M-Lab branding for a while because I thought it was part of the page.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[_layouts/ndt-test.html, line 40 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdDBTu--LaNj1QLD3j:-KDdFiGRFTeE7iff-TrE:1566653160) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/e55599b70a5947ad2c58ac3738542f5ca5d8dde7/_layouts/ndt-test.html#L40)):*
@shredtechular - can you help me understand the logic of how we're handling not letting the test begin until the call is completed? I see how we're handling call failure, but what if the connection is slow and the user hits "start test" before the request completes?

---

*[_layouts/ndt-test.html, line 43 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdHL_Sc3_PnAdpOdxd:-KDdHL_Sc3_PnAdpOdxe:-564236876) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L43)):*
Is jQuery available in this context? Can we use jQuery selectors rather than `getElementById`?

---

*[_layouts/ndt-test.html, line 44 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdFcjBbBd8XpXC2bzB:-KDdFcjBbBd8XpXC2bzC:-604810803) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L44)):*
* We should consistently use single-quotes
* stay < 80 columns

https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Code_formatting

(ditto for rest of PR)

---

*[_layouts/ndt-test.html, line 65 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdGcDT881swfQ7Nceu:-KDdGcDT881swfQ7Ncev:-186906264) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L65)):*
We should be following JSDoc conventions for function comments
https://google.github.io/styleguide/javascriptguide.xml?showone=Comments#Comments

---

*[_layouts/ndt-test.html, line 77 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdI5wUIHgpK92RLgbg:-KDdI5wVb7Tc6h7ZqX-v:-1109621083) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L77)):*
Should this be `innerText`?

---

*[_layouts/ndt-test.html, line 85 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdG4oF86iMX1lfxGpP:-KDdG4oF86iMX1lfxGpQ:-755870759) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L85)):*
stray whitespace

---

*[_layouts/ndt-test.html, line 106 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdD_dVTdCbzIMhGgPj:-KDdGCmUpjy05XKKjxe8:1095069529) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L106)):*
+1 to @georgiamoon' text.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KDdHdMKjKbMB-n7p_kV:-1533555501)*

**Comment by critzo** [comment]
Regarding the UI items, I agree with @mtlynch on 1 and 2, but not really sure I agree about 3. 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KDdMBQaIdzmkUTwbM7M:1141622573)*

**Comment by shredtechular** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[_layouts/ndt-test.html, line 40 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdDBTu--LaNj1QLD3j:-KDd_N3yUXOtc53-dPrm:5979587) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/e55599b70a5947ad2c58ac3738542f5ca5d8dde7/_layouts/ndt-test.html#L40)):*
Basically, logic is that the "Start" button is not shown to the user in the widget until the ajax call is completed or timed out.  If the call is successful, then the start test will be shown and if it times out, then the failure message is shown.  Does that answer you question?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[_layouts/ndt-test.html, line 40 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdDBTu--LaNj1QLD3j:-KDdeSbVyMHYQ0QC4pCv:2125520409) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/e55599b70a5947ad2c58ac3738542f5ca5d8dde7/_layouts/ndt-test.html#L40)):*
Can you give me a pointer to where that logic is implemented? I couldn't find it in the code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by shredtechular** [comment]
@critzo, how were you embedding the widget, were you using: 
`<iframe src="//www.measurementlab.net/p/ndt-ws.html" width="750" height="500" align="middle"></iframe>`
or 
`<iframe src="//shredtechular.github.io/m-lab.github.io/p/ndt-ws.html" width="750" height="500" align="middle"></iframe>` 

The generator is using a config setting to get the domain in Jekyll so that is why it isn't dynamic between forks.  If we want that to be dynamic between forks, then we would probably need extra js to accomplish that which seemed unnecessary to me?

@mtlynch, 
> We don't have a widget repo yet. We have the NDT repo, but the ultimate goal there is to remove all UI logic, so it should have no knowledge of any widgets. Process I had in mind was:

okay, that makes sense I think on the process, will concentrate on #1 for this PR then.  I think we are on the same page, but will digest more of that in the next PR.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KDdfHz1hDw---F5quNu:1727797252)*

**Comment by critzo** [comment]
@shredtechular Ah. I had just copied the text in the box. Changing it to your fork displays everything as expected. Thanks!

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KDdl3M-8wN4qcJEF8mD:-366817463)*

**Comment by shredtechular** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[_layouts/ndt-test.html, line 40 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdDBTu--LaNj1QLD3j:-KDdki2_TL4BkFq3dEHs:2033864434) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/e55599b70a5947ad2c58ac3738542f5ca5d8dde7/_layouts/ndt-test.html#L40)):*
Not sure if I'm doing this in the proper way in Reviewable, however, the start sections are hidden by default in the css (css/ndt-test.css - line 137).  Then either the failure or start sections are shown via js (_layouts/ndt-test.html - lines 39 - 55).

Maybe from a future proofing standpoint when ui is separated from logic, though, we want to hide those via js by default?  Would that be better?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by georgiamoon** [comment]
Re: Michael's UI comments:
> Other thoughts on the UI (wait for @georgiamoon or @critzo for authoritative decisions here as I should not be trusted with UI decisions):
> The "embed" UI feature should be WAY smaller. Like 1% of users will be interested in embedding this widget on a site, so suggest making it just a small button labeled "Embed" then then it pops more UI explaining how to do it when the user actually clicks it
> Suggest "Begin Speed Test" rather than "Begin Network Diagnostics"
> Consider a 1px border around the widget. I have trouble understanding where the page ends and the widget begins, so I actually didn't notice the M-Lab branding for a while because I thought it was part of the page.

+1 

Having a link to an "embed instructions page" would be ideal, because then we can send that link to people who ask about this, who are the 1~5%, but without detracting from the 90~95% experience.

A border would help a lot. It'd be great to add something like that for this iframe, but not all embedded frames.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KDyC0TgkbpJ5ZOq-YWh:746528499)*

**Comment by salarcon215** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[_layouts/ndt-test.html, line 106 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdD_dVTdCbzIMhGgPj:-KEBOeUTBEr2PiGneM-N:458568125) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L106)):*
Tiny change:

Oops!! Something went wrong. There was a network connectivity issue that prevented the NDT test from loading in your browser.

Please try to run the test again by clicking the Try Again button.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by shredtechular** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[_layouts/ndt-test.html, line 43 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdHL_Sc3_PnAdpOdxd:-KGCrmMh2IHCqA57tGNP:-1465795025) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L43)):*
Done.  Converted to using JQuery selectors rather than vanilla js.

---

*[_layouts/ndt-test.html, line 44 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdFcjBbBd8XpXC2bzB:-KGCs-tYMPEb9SRRo3KB:-1452678676) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L44)):*
Done.  Consistently using single quotes now with the JQuery selectors as well as ensured everything that is possible to stay under 80 columns is formatted that way.

---

*[_layouts/ndt-test.html, line 65 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdGcDT881swfQ7Nceu:-KGCsFFgVwy1cCIo3fYN:-2024192856) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L65)):*
Done.  Following JSDoc conventions for function and inline comments.

---

*[_layouts/ndt-test.html, line 77 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdI5wUIHgpK92RLgbg:-KGCsOX6p0EkcbM7uxb5:1007178658) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L77)):*
Done. Went ahead and used JQuery text() function instead since we are using JQuery here.

---

*[_layouts/ndt-test.html, line 85 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdG4oF86iMX1lfxGpP:-KGCsW8anLINCe2pKwkS:599193994) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L85)):*
Done.  whitespace removed.

---

*[_layouts/ndt-test.html, line 106 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-KDdD_dVTdCbzIMhGgPj:-KGCsc1dXDuJbuuymclg:-530330393) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/78277fb6bf4e8c704cce469bd79c61e1ab7089c6/_layouts/ndt-test.html#L106)):*
Done.  Used @georgiamoon text for error messaging

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111)*

**Comment by shredtechular** [comment]
I made an embed link on the starting screen of the widget so that users can click on that and then see the iframe code they can copy/paste.  We can check to see if there is a hash/querystring in the URL to see if that exists then show the embed code/instructions, however, doing this within the widget seems a little counter-intuitive since the widget is being included with an iframe and we would have to pass that from the main page into the iframe.

If we are looking for a "separate embed instructions page" then it seems like this would be better off "outside" the widget functionality and we probably would want to keep the entire "embeddable" feature outside the scope of the widget.  Therefore, I would recommend adding the embed instructions to the /tools/ndt/ page itself rather than the widget if that is desired.  For now, I added the embed button to the widget itself per the original issue description (https://github.com/m-lab/m-lab.github.io/issues/92), "Add a button to the widget that generates the HTML required for embedding".  If we want to revisit this and only add the button to the page and not the widget though, we can revisit that piece.

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KGCswhjKEbdu3sd8pNd:-381109377)*

**Comment by critzo** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/111#-:-KGDCv8NtTCPLbJsn0g0:1417088721)*

**Pull request merged**
