### PR TITLE
grammar, style, link corrections to FAQ page

### PR DESCRIPTION
**Pull request by georgiamoon**
Updated PR for grammar, style & links from gh-pages branch

@critzo

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/122)

### CODE REVIEW

**Comment by critzo** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122#-:-KE1lGl0rthNive6Y-YF:1417088721)*

**Comment by critzo** [comment]
@georgiamoon Looks good to me. The Travis error about a bad link on who/index.html to https://www/isc.org seems like an anomaly. That URL is resolving now, so I wonder if you add a trivial commit to have Travis run again, it would go away.

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[_pages/faq.md, line 50 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122#-KE1lWO6WH3Nec63LKmd:-KE1lWO6WH3Nec63LKme:-1688353511) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/84063064e828a2976eaadb960b07856ffbd454a6/_pages/faq.md#L50)):*
Suggest linking "Network Diagnostic Test (NDT)" to "http://www.measurementlab.net/tools/ndt/"

---

*[_pages/faq.md, line 70 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122#-KE1kMkqlHSnTQqyk7hr:-KE1kMkqlHSnTQqyk7hs:1702225938) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/84063064e828a2976eaadb960b07856ffbd454a6/_pages/faq.md#L70)):*
We have way more raw data than this:
http://www.measurementlab.net/data/gcs/

Suggest just directing user to that page

---

*[_pages/faq.md, line 87 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122#-KE1jNF1DpvJELGTvrZC:-KE1jNF2MA5-0qsXQHb6:-351456339) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/84063064e828a2976eaadb960b07856ffbd454a6/_pages/faq.md#L87)):*
What's with all the dashes in this paragraph? They seem extraneous.

Suggest breaking it up so it's like:

>All performance tests have two parts:
>* **client** - This is the software that runs on the user's machine and shows the user their speed results.
>* **server** - This is the computer on the Internet with which the client connects to complete the test.

---

*[_pages/faq.md, line 93 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122#-KE1l61KSesBjwdL5ShW:-KE1l61KSesBjwdL5ShX:-1840204931) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/84063064e828a2976eaadb960b07856ffbd454a6/_pages/faq.md#L93)):*
Suggest

* "This way, M-Lab is able to" -> "This allows M-Lab to"
* "they could expect" -> "they can expect"

---

*[_pages/faq.md, line 97 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122#-KE1j3mz3Dw50fiIdNzq:-KE1j3n-Axr8rudoeZdS:1678408214) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/84063064e828a2976eaadb960b07856ffbd454a6/_pages/faq.md#L97)):*
This link does not explain NDT. The link should probably go [here](https://github.com/ndt-project/ndt/wiki/NDTTestMethodology) and we should take out "M-Lab's"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/122)*

**Comment by mtlynch** [comment]
Continuing in PR #123

**Pull request closed without merging**
