### PR TITLE
Adding BigQuery usage examples

### PR DESCRIPTION
**Pull request by mtlynch**
This adds BigQuery usage examples. The examples are adapted from the examples here:

https://github.com/m-lab/mlab-wikis/blob/master/BigQueryMLabDataset.md

But they've been significantly refactored and adjusted to query the fast tables (per project) instead of the legacy tables (per month).

[Review on Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/3)

### CODE REVIEW

**Comment by georgiamoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[_pages/bigquery_examples.md, line 7 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9T9If55N1Ck8AAU75t:-K9T9If55N1Ck8AAU75u:-1388810068) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L7)):*
Is there an intro sentence to put before this? It seems not to follow the header.

---

*[_pages/bigquery_examples.md, line 8 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9T9UfA2tJHAQo1sFHH:-K9T9UfA2tJHAQo1sFHI:510025884) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L8)):*
ibid. Not sure why I need this yet, as I haven't  seen/walked through the query yet.

---

*[_pages/bigquery_examples.md, line 29 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9T9h429AJ7vDWWDcuE:-K9T9h429AJ7vDWWDcuF:1940181283) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L29)):*
here is where i'd put those function notes, since here is where they get used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3)*

**Comment by georgiamoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[_pages/bigquery_examples.md, line 35 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9TAbuX1BS7pNQ3RoAU:-K9TAbuX1BS7pNQ3RoAV:-1759554422) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L35)):*
I'm getting an error in BQ on this line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3)*

**Comment by georgiamoon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[_pages/bigquery_examples.md, line 35 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9TAbuX1BS7pNQ3RoAU:-K9TBCh8xshW6c8goVvk:-1942052486) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L35)):*
Errors:
query: Encountered " <ID> "web100_log_entry.connection_spec.remote_ip "" at line 0, column 0. Was expecting: <EOF> (error code: invalidQuery)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3)*

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[_pages/bigquery_examples.md, line 7 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9T9If55N1Ck8AAU75t:-K9TDhVVwRLZDd1mK_2q:307453015) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L7)):*
Got the ordering mixed up.  Fixed!

---

*[_pages/bigquery_examples.md, line 8 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9T9UfA2tJHAQo1sFHH:-K9TDvrQR9DbUTKbMs72:-497468049) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L8)):*
Fixed

---

*[_pages/bigquery_examples.md, line 29 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9T9h429AJ7vDWWDcuE:-K9TDaQZoCzAazvQuBFP:494933409) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L29)):*
Whoops fixed.

---

*[_pages/bigquery_examples.md, line 35 \[r1\]](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-K9TAbuX1BS7pNQ3RoAU:-K9TD3BcR4cq_CRpl37R:989168689) ([raw file](https://github.com/m-lab/m-lab.github.io/blob/b36a1a51ab48687003a031a5093b513ec4e6969f/_pages/bigquery_examples.md#L35)):*
Ah, stray `AND`. Fixed!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3)*

**Comment by georgiamoon** [comment]
LGTM!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/m-lab.github.io/3#-:-K9TF74AptF99L8nPyD2:-492975224)*

**Pull request merged**
