### PR TITLE
Adds blog post about the 10Gb/1Gb switch discard issue

### PR DESCRIPTION
**Pull request by pboothe**
Depends on #397 .  To be reviewed after that one is submitted.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/m-lab.github.io/398)

### CODE REVIEW

**Comment by critzo** [comment]
This looks good @pboothe with some comments below. I've left @stephen-soltesz comments in re: whether notebooks can be hosted easily on the website with that plugin/gem. 

Re: this PR, when we have a post within a new month, we need to add a new data-archive page for the month. Since this is the first post in this month, adding the page: `_pages/dates/2018-09.md` with the content below will allow Travis to build without error:
```
---
layout: blog-date-archive
title: "September 2018"
permalink: /blog/2018/09/
archive-name: September 2018
archive-type: Monthly
breadcrumb: blog
---
```
Additionally, your blog post should have the following 'front matter' at the top, with appropriate values substituted for <bracketed items> :
```
---
layout: blog
title: "<post title>"
author: "<post author>"
date: 2018-09-10
breadcrumb: blog
categories:
  - <tag 1>
  - <tag 2>
  - <etc>
---
```
You can review existing categories/tags in: `_pages/categories/`. If you're adding a new category, a corresponding category page needs to also be added to this folder.

Lastly, the post should also have a breakpoint set using the text `<!--more-->` where the post should break on the front page summary.

**Comment by pboothe** [comment]
PTAL

**Comment by pboothe** [comment]
Adding Georgia because Chris is OoO

**Comment by pboothe** [comment]
Travis is reporting green, but is not doing so here. Weird.

We have a green Travis build and a LGTM. Submitting.

**Pull request merged**
